
export enum SlotType {
  CONSULTATION = 'Consultation',
  RCP = 'RCP',
  MACHINE = 'Machine', // Legacy, can be mapped to activity
  ACTIVITY = 'Activity', // Generic Activity (Astreinte, Unity, Workflow)
  OTHER = 'Other'
}

export enum Period {
  MORNING = 'Matin',
  AFTERNOON = 'Après-midi'
}

export enum DayOfWeek {
  MONDAY = 'Lundi',
  TUESDAY = 'Mardi',
  WEDNESDAY = 'Mercredi',
  THURSDAY = 'Jeudi',
  FRIDAY = 'Vendredi'
}

export interface Doctor {
  id: string;
  name: string;
  specialty: string[];
  color: string;
  // Exclusions
  excludedDays: DayOfWeek[]; // Days they don't work (e.g. 80%)
  excludedActivities: string[]; // Activity IDs they don't do
  excludedSlotTypes?: SlotType[]; // NEW: Specific exclusions (Consult, RCP...) - affect suggestions only, not existing rules
}

export interface Unavailability {
  id: string;
  doctorId: string;
  startDate: string; // ISO string YYYY-MM-DD
  endDate: string;   // ISO string YYYY-MM-DD
  period?: 'ALL_DAY' | Period; // NEW: Granularity of absence
  reason: string;
}

export interface ActivityDefinition {
  id: string;
  name: string;
  granularity: 'HALF_DAY' | 'WEEKLY'; // Week = 1 doctor for whole week
  allowDoubleBooking: boolean; // If true, doesn't trigger conflict (e.g. Supervision)
  color: string;
  isSystem?: boolean; // If true, cannot be deleted (e.g. Astreinte basic)
}

export interface RcpDefinition {
    id: string;
    name: string;
    frequency: 'WEEKLY' | 'BIWEEKLY'; // Every week or every 2 weeks
    weekParity?: 'ODD' | 'EVEN'; // If Bi-weekly, which weeks?
}

// The "Rule" or "Base Responsibility" for fixed slots (Consult/RCP)
export interface ScheduleTemplateSlot {
  id: string;
  day: DayOfWeek;
  period: Period;
  time?: string;
  location: string;
  type: SlotType;
  defaultDoctorId: string | null;
  secondaryDoctorIds?: string[]; // Used for 2nd and 3rd doctor
  doctorIds?: string[]; // NEW: Explicit list of assigned doctors [doc1, doc2, doc3]
  backupDoctorId?: string | null; // NEW: Backup doctor who receives notifications
  subType?: string;
  isRequired?: boolean;
  isBlocking?: boolean; // NEW: If false, does not trigger double booking conflict
  frequency?: 'WEEKLY' | 'BIWEEKLY';
}

// The Actual Generated Slot for a specific date
export interface ScheduleSlot {
  id: string;
  date: string;
  day: DayOfWeek;
  period: Period; 
  time?: string; 
  location: string; 
  type: SlotType;
  assignedDoctorId: string | null; 
  secondaryDoctorIds?: string[]; 
  backupDoctorId?: string | null; // Carried over from template
  subType?: string; 
  isGenerated?: boolean;
  activityId?: string; // Link to ActivityDefinition
  isLocked?: boolean; // If manually overridden
  isBlocking?: boolean; // Inherited from template
  isClosed?: boolean; // NEW: Explicitly closed by user
  isUnconfirmed?: boolean; // NEW: If generated by default but not confirmed by anyone
}

export interface Conflict {
  id: string;
  slotId: string;
  doctorId: string;
  type: 'DOUBLE_BOOKING' | 'UNAVAILABLE' | 'COMPETENCE_MISMATCH';
  description: string;
  severity: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface ReplacementSuggestion {
  originalDoctorId: string;
  suggestedDoctorId: string;
  reasoning: string;
  score: number;
}

export interface Holiday {
    date: string; // MM-DD or YYYY-MM-DD
    name: string;
}

// History of shifts count: { doctorId: { activityId: count } }
export type ShiftHistory = Record<string, Record<string, number>>;

// Persistent Manual Overrides: { slotId: doctorId }
export type ManualOverrides = Record<string, string>;

// RCP Attendance: { slotId: { doctorId: 'PRESENT' | 'ABSENT' } }
export type RcpStatus = 'PRESENT' | 'ABSENT';
export type RcpAttendance = Record<string, Record<string, RcpStatus>>;

// NEW: RCP Exceptions (Move or Cancel specific instances)
export interface RcpException {
    rcpTemplateId: string;
    originalDate: string; // The date it WOULD have been
    newDate?: string; // If moved
    newPeriod?: Period; // If moved
    isCancelled?: boolean;
}

export interface AppContextType {
  doctors: Doctor[];
  addDoctor: (d: Doctor) => void;
  updateDoctor: (d: Doctor) => void;
  removeDoctor: (id: string) => void; // NEW
  currentUser: Doctor | null;
  schedule: ScheduleSlot[]; // Base schedule (usually calculated from a default date, but pages use local)
  template: ScheduleTemplateSlot[];
  unavailabilities: Unavailability[];
  conflicts: Conflict[];
  rcpTypes: RcpDefinition[];
  postes: string[]; // List of consultation locations (Box 1, Box 2, Scanner...)
  addPoste: (name: string) => void;
  removePoste: (name: string) => void; 
  activityDefinitions: ActivityDefinition[];
  addActivityDefinition: (a: ActivityDefinition) => void;
  updateSchedule: (newSchedule: ScheduleSlot[]) => void;
  updateTemplate: (newTemplate: ScheduleTemplateSlot[]) => void;
  addUnavailability: (u: Unavailability) => void;
  removeUnavailability: (id: string) => void;
  setCurrentUser: (d: Doctor | null) => void;
  addRcpType: (name: string) => void;
  updateRcpDefinition: (def: RcpDefinition) => void;
  removeRcpType: (id: string) => void;
  renameRcpType: (oldName: string, newName: string) => void;
  shiftHistory: ShiftHistory; // Past history for equity
  manualOverrides: ManualOverrides;
  setManualOverrides: (overrides: ManualOverrides) => void;
  importConfiguration: (data: any) => void;
  rcpAttendance: RcpAttendance; // NEW
  setRcpAttendance: (att: RcpAttendance) => void; // NEW
  rcpExceptions: RcpException[]; // NEW
  addRcpException: (ex: RcpException) => void; // NEW
  removeRcpException: (templateId: string, originalDate: string) => void; // NEW helper
}